### ISSUE TITLE
Takeover/moving

### ISSUE THREAD

**Issue by SvanteRichter** [LulububuSoftwareGmbH/boltredirector#11]
Hey,

Your extension has been very useful for a great number of bolt users, so to keep maintenance up I hope to move the canonical place to https://github.com/SahAssar/boltredirector. 

Thanks

**Comment by mikerockett** [comment]
Hi SahAssar,

You are more than welcome to do so, thank you for offering. :)

Please would you delete your repo so I can transfer ownership of the original repo to you? This will make the repo canonical under your name (including forks, etc.).

I am not sure how canonicalisation works in terms of the Bolt extensions site - if you have any insight with regards to that, it would be most helpful and appreciated.

Thanks,
Michael

**Comment by SvanteRichter** [comment]
Hey Mike,

I've deleted my fork, so transferring it should work now. I'm talking with rossriley right now on solving it on the extension site, so that should be solved soon.

Thanks!

**Comment by mikerockett** [comment]
I have sent the transfer request to you. I had to move the repo to my personal account first - GH doesn't support Organisation -> Other User transfers yet.

Thanks again - glad you are in a position to take over the extension. :+1:

**Comment by mikerockett** [comment]
Thanks, I see the transfer is complete. :+1:

**Comment by SvanteRichter** [comment]
It's an extension that has helped me many times, thanks for making writing it! :smile:

**Comment by mikerockett** [comment]
You're most welcome, Svante. :+1:
