### ISSUE TITLE
Compatibility with Bolt v3

### ISSUE THREAD

**Issue by HonzaMikula** [LulububuSoftwareGmbH/boltredirector#12]
Is there a plan to make this extension compatible with Bolt v3?

Thanks.

**Comment by mikerockett** [comment]
Ping @SahAssar: Do you still have plans to [migrate to v3](https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/9)? If you don't have the time, I can get back on-board to migrate it for you, but will need to bring myself back up to speed with v2-v3 changes in the extension system.

**Comment by SvanteRichter** [comment]
@mikerockett @HonzaMikula Yep, I plan to do it soon, I've just been busy with porting the menueditor and bolt core work, but I'll get this one done in the coming weeks.

**Comment by mikerockett** [comment]
@SahAssar Great; please let me know if you run into any troubles.

**Comment by miky-btc** [comment]
Cool, glad to hear that. Thanks.

**Comment by SvanteRichter** [comment]
I've tagged a beta release (I still need more testing before tagging a stable, and some more config options), please try it out if you feel like it, and lemme know if you run into any issues!

**Comment by mikerockett** [comment]
Have just had a look at the release code - very nice work Svante. Much cleaner now, too. :+1:

**Comment by SvanteRichter** [comment]
I've tagged a release now, in my testing everything works as it should. If there are issues with it please open an issue and I'll have a look :)
