### ISSUE TITLE
Bug: Crash in match method for invalid regular expression

### ISSUE THREAD

**Issue by blaues0cke** [LulububuSoftwareGmbH/boltredirector#26]
```
     *
     * @return bool
     */
    public function match($path)
    {
        return preg_match("~^" . $this->computedWildcards . "$~i", $path);
    }
```

We may should add a `trycatch` or `@preg_match` around this to avoid the whole site to get broken when the user enters a invalid rule?

![image](https://user-images.githubusercontent.com/5159398/66388913-6b54e400-e9c7-11e9-8396-bcdb3bc457d2.png)

The user entered this configuration to make it crash:

```
?page_id=97:
    from: '/?page_id=97'
    to: '/'
                    
?page_id=678:
    from: '/?page_id=678'
    to: '/'
```

**Comment by SvanteRichter** [comment]
Sure, open a PR and I'll have a look! Even better would be validation, but that'd be harder.
