### ISSUE TITLE
Application as Maintainers

### ISSUE THREAD

**Issue by Spomsoree** [LulububuSoftwareGmbH/boltredirector#28]
Hello,

we are a small software company from germany (https://github.com/LulububuApps).
Since we rely on bolt and use this package in every bolt project, we would like to offer to continue the maintenance of this package.

We gladly answer your questions, if you have any.

**Comment by SvanteRichter** [comment]
Awesome! I'll transfer it over to the LulububuApps org!

**Comment by SvanteRichter** [comment]
You'll have to delete your fork first though, since that is taking up the name LulububuApps/boltredirector

**Comment by Spomsoree** [comment]
I'll do that, give me a second.

**Comment by Spomsoree** [comment]
The fork is deleted now.

**Comment by SvanteRichter** [comment]
Hmm, now I'm getting " You don’t have the permission to create public repositories on LulububuApps" when I try to transfer. I've invited you to this org so that you can initiate the transfer.

**Comment by Spomsoree** [comment]
It worked!

I've successfully transferred it.

**Comment by SvanteRichter** [comment]
Great! :)

**Comment by SvanteRichter** [comment]
Also please contact @bobdenotter for help with getting the marketplace entry for it handed over to you guys :)

**Comment by Spomsoree** [comment]
Alright, I'll do that. Thank you.
