### ISSUE TITLE
Add support for logging all redirects in the database

### ISSUE THREAD

**Issue by mikerockett** [LulububuSoftwareGmbH/boltredirector#5]
Just curious to know if this idea is viable. Perhaps for campaign purposes?

**Comment by mikerockett** [comment]
@bobdenotter: What do you think?

**Comment by bobdenotter** [comment]
Sounds like a good idea. :-)

**Comment by mikerockett** [comment]
Okay, will implement it soon.

Also planning to separate the code into 'modules' and doing a bit of a clean-up.

**Comment by bobdenotter** [comment]
:+1:
